### ISSUE TITLE
Can't build store product view for new product

### ISSUE THREAD

**Issue by yqszt** [EasyAbp/EShop#264]
I try to run EShop sample, and try to create a new product, then i found an error like that:

> 
[17:47:34 ERR] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.MinBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer)
   at System.Linq.Enumerable.MinBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at EasyAbp.EShop.Products.Products.ProductViewAppService.GetCacheDurationOrNullAsync(List`1 productViews, DateTime now)
   at EasyAbp.EShop.Products.Products.ProductViewAppService.BuildStoreProductViewsAsync(Guid storeId)
   at EasyAbp.EShop.Products.Products.ProductViewAppService.GetListAsync(GetProductListInput input)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.ProceedByLoggingAsync(IAbpMethodInvocation invocation, AbpAuditingOptions options, IAuditingHelper auditingHelper, IAuditLogScope auditLogScope)
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at lambda_method4325(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[17:47:34 INF] Executing ObjectResult, writing value of type 'Volo.Abp.Http.RemoteServiceErrorResponse'.
[17:47:34 INF] Executed action EasyAbp.EShop.Products.Products.ProductViewController.GetListAsync (EasyAbp.EShop.Products.HttpApi) in 995.6593ms
[17:47:34 INF] Executed endpoint 'EasyAbp.EShop.Products.Products.ProductViewController.GetListAsync (EasyAbp.EShop.Products.HttpApi)'

The root cause is missing sku for new product when fill price with real price.
I try to fix it with an empty ProductViewDiscountModels,  is it a right way?
![image](https://github.com/EasyAbp/EShop/assets/15865671/a2d05ee0-a00d-42cf-8d5f-a5816c389592)

**Comment by gdlcf88** [comment]
Hi, I guess you are upgrading from the old version EShop.

![image](https://github.com/EasyAbp/EShop/assets/30018771/a51328fe-9c87-4dfe-8f85-048825ad82e5)

The exception you got may cause by these two columns with null values. Please try to truncate the ProductView table, and the newly generated entities are expected to be `[]` if the discount info is empty.

**Comment by yqszt** [comment]
> Hi, I guess you are upgrading from the old version EShop.
> 
> ![image](https://user-images.githubusercontent.com/30018771/241556661-a51328fe-9c87-4dfe-8f85-048825ad82e5.png)
> 
> The exception you got may cause by these two columns with null values. Please try to truncate the ProductView table, and the newly generated entities are expected to be `[]` if the discount info is empty.

Hello, It not this issue,  actually i'm using the latest version from dev, i just change database to Mysql, and i checked the logic that how to build the product view, firstly create a product info, and when i first get a list of product, the program would be bulid a product view entity and store cache it through the BuildStoreProductViewsAsync method.
![image](https://github.com/EasyAbp/EShop/assets/15865671/67c4b0ae-eaa3-454a-a9c0-538e0896570e)
This method build product view from product entity not product view entity. so the root cause is here, when product mapping to product view, the ProductDiscounts property should be null.
![image](https://github.com/EasyAbp/EShop/assets/15865671/f31ad5cb-22e4-4e42-a77f-5067006175dd)
and then, the program to fill the real price to the product view, the real price come from sku info. but the new one does't have any sku info, so there is no any process logic for this view, the  ProductDiscounts property still null.
![image](https://github.com/EasyAbp/EShop/assets/15865671/02a36eee-6ab7-48a8-b1de-5f42a977a5bb)
finally the null value store to database, and application throw a NullReferenceException.
![image](https://github.com/EasyAbp/EShop/assets/15865671/d4742841-e2ef-4fc8-96ec-b05a607a936a)

**Comment by gdlcf88** [comment]
Well, I see now. I will fix this problem. Thank you for reporting this.
